# Generated by Django 2.2.10 on 2021-03-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bar_code',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='e_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='location_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
