# Generated by Django 2.2.10 on 2021-03-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210323_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bar_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
