# Generated by Django 2.2.10 on 2021-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210323_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_order',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
