# Generated by Django 2.2.10 on 2021-03-29 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_item_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL)),
                ('lab_inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_inviter', to='inventory.Lab')),
            ],
        ),
    ]
