# Generated by Django 2.2.10 on 2021-03-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_labinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinvite',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=100),
        ),
    ]
