# Generated by Django 2.2.10 on 2021-03-31 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_labinvite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.Lab'),
        ),
        migrations.AlterField(
            model_name='item',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='inventory.Inventory'),
        ),
        migrations.AlterField(
            model_name='item_change_log',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_change_log', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='item_order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='item_order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labinvite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_invite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labinvite',
            name='lab_inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_invite', to='inventory.Lab'),
        ),
    ]
