# Generated by Django 2.2.10 on 2021-04-03 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210331_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='lab',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.Lab'),
        ),
        migrations.AlterField(
            model_name='item',
            name='inventory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='inventory.Inventory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
