# Generated by Django 2.2.10 on 2021-04-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210403_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='e_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
