# Generated by Django 2.2.10 on 2021-04-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20210403_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_change_log',
            old_name='quantity',
            new_name='quantity_changed',
        ),
        migrations.AddField(
            model_name='item_change_log',
            name='new_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
